import os
import datetime

def save_document(response_txt: str, directory: str = './output'):
    """Export travel plan to Markdown file with proper formatting"""
    os.makedirs(directory, exist_ok=True)

    markdown_content = f"""# AI Travel Plan
    
    -----------------
    
    {response_txt}

    -----------------
    
    THIS TRAVEL PLAN WAS GENERATED BY AI. PLEASE VERIFY ALL INFORMATION.
    """

    try:
        timestamp=datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename=f"{directory}/AI_TRAVEL_PLAN_{timestamp}.md"
        print(filename)

        with open(filename, 'w', encoding='utf-8') as f:  # encoding using utf-8 ensuring non ASCII symbols are corrctly stored and retrieved
            f.write(markdown_content)

        print(f"Markdown file saved as: {filename}")

    except Exception as e:
        print(f"Error saving markdown file: {e}")
        return None